version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/app/data/db
    restart: unless-stopped
    networks:
      - training
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - training
  
  worker-1:
    container_name: worker-1
    build: ./worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - training
  
  worker-2:
    container_name: worker-2
    build: ./worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - training
  
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - training

volumes:
  mongodb:

networks:
  training:
    name: training
    driver: bridge